# Generated by Django 6.0.6 on 2026-06-28 18:52

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Certification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('issuer', models.CharField(choices=[('ibm', 'IBM / Coursera'), ('google', 'Google / Coursera'), ('ec_council', 'EC-Council'), ('microsoft', 'Microsoft'), ('other', 'Other')], default='other', max_length=30)),
                ('issuer_display', models.CharField(blank=True, max_length=200)),
                ('credential_url', models.URLField(blank=True, null=True)),
                ('issue_date', models.DateField(blank=True, null=True)),
                ('description', models.TextField(blank=True)),
                ('badge_icon', models.CharField(default='trophy', max_length=10)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order', '-issue_date'],
            },
        ),
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=300)),
                ('message', models.TextField()),
                ('status', models.CharField(choices=[('new', 'New'), ('read', 'Read'), ('replied', 'Replied'), ('archived', 'Archived')], default='new', max_length=20)),
                ('submitted_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=200)),
                ('role', models.CharField(max_length=200)),
                ('experience_type', models.CharField(choices=[('internship', 'Internship'), ('fulltime', 'Full-Time'), ('parttime', 'Part-Time'), ('freelance', 'Freelance')], default='internship', max_length=20)),
                ('location', models.CharField(default='Faisalabad, Pakistan', max_length=200)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('is_current', models.BooleanField(default=False)),
                ('responsibilities', models.TextField(help_text='One bullet per line')),
                ('tech_used', models.CharField(blank=True, max_length=500)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order', '-start_date'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('category', models.CharField(choices=[('ml', 'Machine Learning / AI'), ('web', 'Web Development'), ('data', 'Data Science / Analytics'), ('security', 'Cyber Security'), ('other', 'Other')], default='ml', max_length=20)),
                ('tagline', models.CharField(max_length=300)),
                ('description', models.TextField()),
                ('tech_stack', models.CharField(max_length=500)),
                ('github_url', models.URLField(blank=True, null=True)),
                ('live_url', models.URLField(blank=True, null=True)),
                ('image_url', models.URLField(blank=True, help_text='Paste a direct image URL (Unsplash, GitHub raw, Cloudinary)', null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='projects/')),
                ('is_featured', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
